#!/bin/sh
# This file is part of the halt program.
# To see the licensing terms, see the COPYING file.

check_current_init()
{
	if [ "$(ps -o comm= 1)" = "runit" ]; then
		selected2="*"
		selected1=" "
	elif [ "$(ps -o comm= 1)" = "init" ]; then
		selected1="*"
		selected2=" "
	else
		printf "\\033[1;31mError:\\033[m Current init is not supported!\\n"
		exit 1
	fi
}

available_init()
{
	printf "Currently available init system(s): \\n"

	[ -x "/sbin/openrc-init" ] && printf " - [\\033[1;32m%s\\033[0m] openrc\\n" "$selected1"
	[ -x "/sbin/runit-init" ] && printf " - [\\033[1;32m%s\\033[0m] runit\\n" "$selected2"
}

select_init()
{
	printf "Select your chosen init: "
	read -r NEXTINIT

	case $NEXTINIT in
		"openrc") ln -sf "openrc-init" "/usr/bin/init" ;;
		"runit") ln -sf "runit-init" "/usr/bin/init" ;;
		*) printf "Init does not exist/is not supported!\\n"; exit 1 ;;
	esac
}

main()
{
	if [ "$(id -u)" != "0" ]; then
		printf "\\033[1;31mError:\\033[m User must be root to run this program!\\n"
		exit 1
	fi
	check_current_init
	available_init
	if [ -x "/usr/bin/openrc-init" ] && [ -x "/usr/bin/runit-init" ]; then
		select_init
	fi
}

main "$@"
